global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/driftq_rules.yml

scrape_configs:
  # DriftQ broker scrape (update target to your broker host if not using compose)
  - job_name: "driftqd"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: /metrics

  # Prometheus self
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
